server:
  port: ${SERVER_PORT}
spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
